// @generated by tools/generate_domain_metadata.py; DO NOT EDIT.
// Metadata only; constants and VM programs remain handwritten.

const PED_MID_OPERATION_INPUTS: [InputDecl; 4] = [
    InputDecl {
        name: "p1",
        semantic_kind: 3,
        same_unit_group: 1,
        unit_required: false,
        constraint: ConstraintKind::GreaterThan,
        constraint_value: WorkRational::from_integer(0),
        detail_id: 1,
    },
    InputDecl {
        name: "p2",
        semantic_kind: 3,
        same_unit_group: 1,
        unit_required: false,
        constraint: ConstraintKind::GreaterThan,
        constraint_value: WorkRational::from_integer(0),
        detail_id: 2,
    },
    InputDecl {
        name: "q1",
        semantic_kind: 4,
        same_unit_group: 2,
        unit_required: false,
        constraint: ConstraintKind::GreaterOrEqual,
        constraint_value: WorkRational::from_integer(0),
        detail_id: 3,
    },
    InputDecl {
        name: "q2",
        semantic_kind: 4,
        same_unit_group: 2,
        unit_required: false,
        constraint: ConstraintKind::GreaterOrEqual,
        constraint_value: WorkRational::from_integer(0),
        detail_id: 4,
    },
];

const PED_MID_OPERATION_CLASSIFICATIONS: [ClassificationDecl; 3] = [
    ClassificationDecl {
        id: 1,
        key: "inelastic",
        program: &CLASS_INELASTIC_PROGRAM,
    },
    ClassificationDecl {
        id: 2,
        key: "unit_elastic",
        program: &CLASS_UNIT_PROGRAM,
    },
    ClassificationDecl {
        id: 3,
        key: "elastic",
        program: &CLASS_ELASTIC_PROGRAM,
    },
];

/// `econ.ped.mid(p1,p2,q1,q2)`.
pub static PED_MID_OPERATION: OperationDecl = OperationDecl {
    id: 301,
    revision: 1,
    key: "econ.ped.mid",
    signature: "econ.ped.mid(p1,p2,q1,q2)",
    method: "midpoint",
    inputs: &PED_MID_OPERATION_INPUTS,
    constants: &PED_CONSTANTS,
    program: &PED_PROGRAM,
    classifications: &PED_MID_OPERATION_CLASSIFICATIONS,
    output_semantic_kind: 10,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// Returns a reviewed economics operation selected into this build.
#[cfg(feature = "econ-specialized")]
#[must_use]
pub fn economics_selected_operation_by_key(key: &[u8]) -> Option<&'static OperationDecl> {
    match key {
        #[cfg(feature = "econ-ped-mid")]
        b"econ.ped.mid" => Some(&PED_MID_OPERATION),
        _ => None,
    }
}
