// @generated by tools/generate_statistics_metadata.py; DO NOT EDIT.
/// Stable internal ID for `sum`; not a pack-local ID.
pub const STATS_KERNEL_SUM: u16 = 1;
/// Stable internal ID for `mean`; not a pack-local ID.
pub const STATS_KERNEL_MEAN: u16 = 2;
/// Stable internal ID for `weighted_mean`; not a pack-local ID.
pub const STATS_KERNEL_WEIGHTED_MEAN: u16 = 3;
/// Stable internal ID for `variance_population`; not a pack-local ID.
pub const STATS_KERNEL_VARIANCE_POPULATION: u16 = 4;
/// Stable internal ID for `variance_sample`; not a pack-local ID.
pub const STATS_KERNEL_VARIANCE_SAMPLE: u16 = 5;
/// Stable internal ID for `standard_deviation_population`; not a pack-local ID.
pub const STATS_KERNEL_STANDARD_DEVIATION_POPULATION: u16 = 10;
/// Stable internal ID for `standard_deviation_sample`; not a pack-local ID.
pub const STATS_KERNEL_STANDARD_DEVIATION_SAMPLE: u16 = 11;
/// Stable internal ID for `covariance_population`; not a pack-local ID.
pub const STATS_KERNEL_COVARIANCE_POPULATION: u16 = 6;
/// Stable internal ID for `covariance_sample`; not a pack-local ID.
pub const STATS_KERNEL_COVARIANCE_SAMPLE: u16 = 7;
/// Stable internal ID for `correlation`; not a pack-local ID.
pub const STATS_KERNEL_CORRELATION: u16 = 8;
/// Stable internal ID for `linear_regression`; not a pack-local ID.
pub const STATS_KERNEL_LINEAR_REGRESSION: u16 = 9;
/// Resolves a reviewed kernel name in the enabled kernel namespace.
#[must_use]
pub fn statistics_kernel_id_by_name(name: &str) -> Option<u16> {
    match name {
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sum"))]
"sum" => Some(STATS_KERNEL_SUM),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean"))]
"mean" => Some(STATS_KERNEL_MEAN),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean-weighted"))]
"weighted_mean" => Some(STATS_KERNEL_WEIGHTED_MEAN),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-pop"))]
"variance_population" => Some(STATS_KERNEL_VARIANCE_POPULATION),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-sample"))]
"variance_sample" => Some(STATS_KERNEL_VARIANCE_SAMPLE),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-pop"))]
"standard_deviation_population" => Some(STATS_KERNEL_STANDARD_DEVIATION_POPULATION),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-sample"))]
"standard_deviation_sample" => Some(STATS_KERNEL_STANDARD_DEVIATION_SAMPLE),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-pop"))]
"covariance_population" => Some(STATS_KERNEL_COVARIANCE_POPULATION),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-sample"))]
"covariance_sample" => Some(STATS_KERNEL_COVARIANCE_SAMPLE),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-corr-pearson"))]
"correlation" => Some(STATS_KERNEL_CORRELATION),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-regression-linear"))]
"linear_regression" => Some(STATS_KERNEL_LINEAR_REGRESSION),
_ => None,
}
}
/// Returns the enabled stable kernel arity contract.
#[must_use]
pub const fn statistics_kernel_contract(kernel_id: u16) -> Option<StatisticsKernelContract> {
match kernel_id {
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sum"))]
STATS_KERNEL_SUM => Some(StatisticsKernelContract { input_count: 1, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean"))]
STATS_KERNEL_MEAN => Some(StatisticsKernelContract { input_count: 1, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean-weighted"))]
STATS_KERNEL_WEIGHTED_MEAN => Some(StatisticsKernelContract { input_count: 2, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-pop"))]
STATS_KERNEL_VARIANCE_POPULATION => Some(StatisticsKernelContract { input_count: 1, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-sample"))]
STATS_KERNEL_VARIANCE_SAMPLE => Some(StatisticsKernelContract { input_count: 1, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-pop"))]
STATS_KERNEL_STANDARD_DEVIATION_POPULATION => Some(StatisticsKernelContract { input_count: 1, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-sample"))]
STATS_KERNEL_STANDARD_DEVIATION_SAMPLE => Some(StatisticsKernelContract { input_count: 1, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-pop"))]
STATS_KERNEL_COVARIANCE_POPULATION => Some(StatisticsKernelContract { input_count: 2, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-sample"))]
STATS_KERNEL_COVARIANCE_SAMPLE => Some(StatisticsKernelContract { input_count: 2, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-corr-pearson"))]
STATS_KERNEL_CORRELATION => Some(StatisticsKernelContract { input_count: 2, output_count: 1 }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-regression-linear"))]
STATS_KERNEL_LINEAR_REGRESSION => Some(StatisticsKernelContract { input_count: 2, output_count: 2 }),
_ => None,
}
}
/// Canonical output ordering for an enabled stable kernel ID.
#[must_use]
pub const fn statistics_kernel_output_names(kernel_id: u16) -> &'static [&'static str] {
match kernel_id {
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sum"))]
STATS_KERNEL_SUM => &["sum"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean"))]
STATS_KERNEL_MEAN => &["mean"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean-weighted"))]
STATS_KERNEL_WEIGHTED_MEAN => &["mean"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-pop"))]
STATS_KERNEL_VARIANCE_POPULATION => &["variance"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-sample"))]
STATS_KERNEL_VARIANCE_SAMPLE => &["variance"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-pop"))]
STATS_KERNEL_STANDARD_DEVIATION_POPULATION => &["standard_deviation"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-sample"))]
STATS_KERNEL_STANDARD_DEVIATION_SAMPLE => &["standard_deviation"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-pop"))]
STATS_KERNEL_COVARIANCE_POPULATION => &["covariance"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-sample"))]
STATS_KERNEL_COVARIANCE_SAMPLE => &["covariance"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-corr-pearson"))]
STATS_KERNEL_CORRELATION => &["correlation"],
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-regression-linear"))]
STATS_KERNEL_LINEAR_REGRESSION => &["slope", "intercept"],
_ => &[],
}
}
