// @generated by tools/generate_statistics_metadata.py; DO NOT EDIT.
// Sources: packs/statistics-core.xsp.json + spec/implementation/statistics-kernel-bindings.json.
// Regenerate: python tools/generate_statistics_metadata.py
// Validate:   python tools/generate_statistics_metadata.py --check
// Pack-local operation IDs are NOT stable kernel IDs. No numeric algorithms are generated.

/// `stats.sum(values)`.
pub static STATS_SUM_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 1,
    revision: 1,
    key: "stats.sum",
    signature: "stats.sum(values)",
    method: "exact_ordered",
    kernel_id: STATS_KERNEL_SUM,
    input_count: 1,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.mean(values)`.
pub static STATS_MEAN_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 2,
    revision: 1,
    key: "stats.mean",
    signature: "stats.mean(values)",
    method: "arithmetic",
    kernel_id: STATS_KERNEL_MEAN,
    input_count: 1,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.mean.weighted(values,weights)`.
pub static STATS_WEIGHTED_MEAN_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 3,
    revision: 1,
    key: "stats.mean.weighted",
    signature: "stats.mean.weighted(values,weights)",
    method: "weighted_arithmetic",
    kernel_id: STATS_KERNEL_WEIGHTED_MEAN,
    input_count: 2,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.var.pop(values)`.
pub static STATS_VARIANCE_POPULATION_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 4,
    revision: 1,
    key: "stats.var.pop",
    signature: "stats.var.pop(values)",
    method: "two_pass_population",
    kernel_id: STATS_KERNEL_VARIANCE_POPULATION,
    input_count: 1,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.var.sample(values)`.
pub static STATS_VARIANCE_SAMPLE_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 5,
    revision: 1,
    key: "stats.var.sample",
    signature: "stats.var.sample(values)",
    method: "two_pass_sample",
    kernel_id: STATS_KERNEL_VARIANCE_SAMPLE,
    input_count: 1,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.sd.pop(values)`.
pub static STATS_STANDARD_DEVIATION_POPULATION_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 6,
    revision: 1,
    key: "stats.sd.pop",
    signature: "stats.sd.pop(values)",
    method: "population",
    kernel_id: STATS_KERNEL_STANDARD_DEVIATION_POPULATION,
    input_count: 1,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.sd.sample(values)`.
pub static STATS_STANDARD_DEVIATION_SAMPLE_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 7,
    revision: 1,
    key: "stats.sd.sample",
    signature: "stats.sd.sample(values)",
    method: "sample",
    kernel_id: STATS_KERNEL_STANDARD_DEVIATION_SAMPLE,
    input_count: 1,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.cov.pop(x,y)`.
pub static STATS_COVARIANCE_POPULATION_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 8,
    revision: 1,
    key: "stats.cov.pop",
    signature: "stats.cov.pop(x,y)",
    method: "population",
    kernel_id: STATS_KERNEL_COVARIANCE_POPULATION,
    input_count: 2,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.cov.sample(x,y)`.
pub static STATS_COVARIANCE_SAMPLE_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 9,
    revision: 1,
    key: "stats.cov.sample",
    signature: "stats.cov.sample(x,y)",
    method: "sample",
    kernel_id: STATS_KERNEL_COVARIANCE_SAMPLE,
    input_count: 2,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.corr.pearson(x,y)`.
pub static STATS_CORRELATION_PEARSON_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 10,
    revision: 1,
    key: "stats.corr.pearson",
    signature: "stats.corr.pearson(x,y)",
    method: "pearson",
    kernel_id: STATS_KERNEL_CORRELATION,
    input_count: 2,
    output_count: 1,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// `stats.regression.linear(x,y)`.
pub static STATS_LINEAR_REGRESSION_OPERATION: StatisticsOperationDecl = StatisticsOperationDecl {
    id: 11,
    revision: 1,
    key: "stats.regression.linear",
    signature: "stats.regression.linear(x,y)",
    method: "least_squares",
    kernel_id: STATS_KERNEL_LINEAR_REGRESSION,
    input_count: 2,
    output_count: 2,
    output_scale: 6,
    rounding_mode: RoundingMode::HalfEven,
};

/// Executable statistics operations in the first fused kernel slice.
pub static OFFICIAL_STATS_OPERATIONS: [&StatisticsOperationDecl; 11] = [
    &STATS_SUM_OPERATION,
    &STATS_MEAN_OPERATION,
    &STATS_WEIGHTED_MEAN_OPERATION,
    &STATS_VARIANCE_POPULATION_OPERATION,
    &STATS_VARIANCE_SAMPLE_OPERATION,
    &STATS_STANDARD_DEVIATION_POPULATION_OPERATION,
    &STATS_STANDARD_DEVIATION_SAMPLE_OPERATION,
    &STATS_COVARIANCE_POPULATION_OPERATION,
    &STATS_COVARIANCE_SAMPLE_OPERATION,
    &STATS_CORRELATION_PEARSON_OPERATION,
    &STATS_LINEAR_REGRESSION_OPERATION,
];

/// Resolves a canonical key against enabled operations.
#[must_use]
#[cfg_attr(
    feature = "stats-specialized",
    allow(unreachable_code, unused_variables)
)]
pub fn statistics_selected_operation_by_key(
    key: &[u8],
) -> Option<&'static StatisticsOperationDecl> {
    match key {
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-sum"
        ))]
        b"stats.sum" => Some(&STATS_SUM_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-mean"
        ))]
        b"stats.mean" => Some(&STATS_MEAN_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-mean-weighted"
        ))]
        b"stats.mean.weighted" => Some(&STATS_WEIGHTED_MEAN_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-var-pop"
        ))]
        b"stats.var.pop" => Some(&STATS_VARIANCE_POPULATION_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-var-sample"
        ))]
        b"stats.var.sample" => Some(&STATS_VARIANCE_SAMPLE_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-sd-pop"
        ))]
        b"stats.sd.pop" => Some(&STATS_STANDARD_DEVIATION_POPULATION_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-sd-sample"
        ))]
        b"stats.sd.sample" => Some(&STATS_STANDARD_DEVIATION_SAMPLE_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-cov-pop"
        ))]
        b"stats.cov.pop" => Some(&STATS_COVARIANCE_POPULATION_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-cov-sample"
        ))]
        b"stats.cov.sample" => Some(&STATS_COVARIANCE_SAMPLE_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-corr-pearson"
        ))]
        b"stats.corr.pearson" => Some(&STATS_CORRELATION_PEARSON_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-regression-linear"
        ))]
        b"stats.regression.linear" => Some(&STATS_LINEAR_REGRESSION_OPERATION),
        _ => None,
    }
}

/// Resolves a pack-local ID (not a kernel ID) against enabled operations.
#[must_use]
#[cfg_attr(
    feature = "stats-specialized",
    allow(unreachable_code, unused_variables)
)]
pub fn statistics_selected_operation_by_id(
    operation_id: u32,
) -> Option<&'static StatisticsOperationDecl> {
    match operation_id {
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-sum"
        ))]
        1 => Some(&STATS_SUM_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-mean"
        ))]
        2 => Some(&STATS_MEAN_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-mean-weighted"
        ))]
        3 => Some(&STATS_WEIGHTED_MEAN_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-var-pop"
        ))]
        4 => Some(&STATS_VARIANCE_POPULATION_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-var-sample"
        ))]
        5 => Some(&STATS_VARIANCE_SAMPLE_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-sd-pop"
        ))]
        6 => Some(&STATS_STANDARD_DEVIATION_POPULATION_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-sd-sample"
        ))]
        7 => Some(&STATS_STANDARD_DEVIATION_SAMPLE_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-cov-pop"
        ))]
        8 => Some(&STATS_COVARIANCE_POPULATION_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-cov-sample"
        ))]
        9 => Some(&STATS_COVARIANCE_SAMPLE_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-corr-pearson"
        ))]
        10 => Some(&STATS_CORRELATION_PEARSON_OPERATION),
        #[cfg(any(
            not(feature = "stats-specialized"),
            feature = "stats-regression-linear"
        ))]
        11 => Some(&STATS_LINEAR_REGRESSION_OPERATION),
        _ => None,
    }
}
