// @generated by tools/generate_statistics_metadata.py; DO NOT EDIT.
{
let square_root_result = match operation.kernel_id {
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-pop"))]
STATS_KERNEL_STANDARD_DEVIATION_POPULATION => Some(statistics_population_standard_deviation(arguments[0], operation.output_scale, operation.rounding_mode)),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sd-sample"))]
STATS_KERNEL_STANDARD_DEVIATION_SAMPLE => Some(statistics_sample_standard_deviation(arguments[0], operation.output_scale, operation.rounding_mode)),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-corr-pearson"))]
STATS_KERNEL_CORRELATION => Some(statistics_pearson_correlation(arguments[0], arguments[1], operation.output_scale, operation.rounding_mode)),
_ => None,
};
if let Some(result) = square_root_result {
return match result {
Ok(result) => statistics_sqrt_success(pack_slot, operation, result),
Err(status) => statistics_failure(pack_slot, operation, status),
};
}
match operation.kernel_id {
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-sum"))]
STATS_KERNEL_SUM => statistics_sum(arguments[0]).map(|value| { exact[0] = value; 1usize }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean"))]
STATS_KERNEL_MEAN => statistics_mean(arguments[0]).map(|value| { exact[0] = value; 1usize }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-mean-weighted"))]
STATS_KERNEL_WEIGHTED_MEAN => statistics_weighted_mean(arguments[0], arguments[1]).map(|value| { exact[0] = value; 1usize }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-pop"))]
STATS_KERNEL_VARIANCE_POPULATION => statistics_population_variance(arguments[0]).map(|value| { exact[0] = value; 1usize }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-var-sample"))]
STATS_KERNEL_VARIANCE_SAMPLE => statistics_sample_variance(arguments[0]).map(|value| { exact[0] = value; 1usize }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-pop"))]
STATS_KERNEL_COVARIANCE_POPULATION => statistics_population_covariance(arguments[0], arguments[1]).map(|value| { exact[0] = value; 1usize }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-cov-sample"))]
STATS_KERNEL_COVARIANCE_SAMPLE => statistics_sample_covariance(arguments[0], arguments[1]).map(|value| { exact[0] = value; 1usize }),
#[cfg(any(not(feature = "stats-specialized"), feature = "stats-regression-linear"))]
STATS_KERNEL_LINEAR_REGRESSION => statistics_linear_regression(arguments[0], arguments[1]).map(|value| { exact[0] = value.slope; exact[1] = value.intercept; 2usize }),
_ => Err(Status::INTERNAL_ERROR),
}
}
