#!/usr/bin/env python3
"""Check descriptor-driven Cargo wiring and generate scalar operation metadata.

Vector Statistics declarations/dispatch are generated by generate_statistics_metadata.
Scalar numeric semantics remain in handwritten kernel operations and the shared VM.
"""
import argparse
import json
from pathlib import Path
import re
import sys

from generate_statistics_metadata import BINDINGS as STATISTICS_BINDINGS
from generate_statistics_metadata import PACK as STATISTICS_PACK
from generate_statistics_metadata import ROOT, load, require, validate_features


def registry(root, name):
    entries = load(root / f'spec/registries/{name}.json')['entries']
    require(len({e['key'] for e in entries}) == len(entries)
            and len({e['id'] for e in entries}) == len(entries), 'duplicate registry entry')
    return {e['key']: e for e in entries}


def integer(value, maximum, label, minimum=0):
    require(type(value) is int and minimum <= value <= maximum, f'invalid {label}')
    return value


def rational(value):
    require(isinstance(value, str) and re.fullmatch(r'-?(0|[1-9][0-9]*)', value),
            'unsupported scalar constant: integer rational required')
    return integer(int(value), 2**63 - 1, 'scalar constant', -(2**63))


def handwritten_array(rust, symbol, kind, item_pattern):
    matches = re.findall(rf'(?m)^const {symbol}: \[{kind}; (\d+)\] =\s*\[(.*?)\];', rust, re.S)
    require(len(matches) == 1, f'missing or duplicate handwritten symbol: {symbol}')
    count, body = matches[0]
    # Full consumption rejects extra expressions, aliases, and conditional entries.
    require(re.fullmatch(rf'\s*(?:{item_pattern}\s*,\s*)*(?:{item_pattern}\s*)?', body),
            f'unsupported handwritten array: {symbol}')
    items = re.findall(item_pattern, body)
    require(len(items) == int(count), f'handwritten array length drift: {symbol}')
    return items


def check_program(rust, symbol, program, opcodes, op, predicate=False):
    expected = []
    depth = 0
    require(isinstance(program, list) and 0 < len(program) <= 64, 'unsupported VM program length')
    for index, instruction in enumerate(program):
        require(isinstance(instruction, list) and instruction and instruction[0] in opcodes,
                'unsupported VM instruction')
        code = opcodes[instruction[0]]
        operand_kind = code['operand']
        require(operand_kind in ('none', 'u24', 'i24'), 'unsupported VM operand encoding')
        require(len(instruction) == (1 if operand_kind == 'none' else 2), 'invalid VM operand arity')
        operand = 0 if operand_kind == 'none' else integer(
            instruction[1], 2**23 - 1 if operand_kind == 'i24' else 2**24 - 1,
            'VM operand', -(2**23) if operand_kind == 'i24' else 0)
        key = code['key']
        require(key != 'arg' or (not predicate and operand < len(op['inputs'])), 'invalid VM argument')
        require(key != 'const' or operand < len(op['constants']), 'invalid VM constant')
        require(key != 'result' or (predicate and operand == 0), 'invalid VM result')
        require((key == 'end') == (index == len(program) - 1), 'invalid VM end')
        require(depth >= code['pop'] and (key != 'end' or depth == 1), 'invalid VM stack')
        depth += code['push'] - code['pop']
        require(depth <= 16, 'unsupported VM stack depth')
        expected.append((code['id'], operand & 0xFFFFFF))
    actual = handwritten_array(rust, symbol, 'Instruction', r'Instruction::new\(\s*(\d+)\s*,\s*(\d+)\s*\)')
    require([(int(a), int(b)) for a, b in actual] == expected, f'handwritten program drift: {symbol}')


def scalar_metadata(op, b, rust, opcodes, semantics, symbols):
    fields = {'key', 'cargo_feature', 'rust_operation_symbol', 'rust_constants_symbol',
              'rust_program_symbol', 'rust_classification_predicates'}
    require(set(b) == fields, 'binding fields must contain only implementation identity')
    require(re.fullmatch(r'econ\.[a-z0-9._-]+', op['key']), 'invalid operation key')
    require(b['cargo_feature'] == op['key'].replace('.', '-'), 'compiler feature convention drift')
    predicates = b['rust_classification_predicates']
    require(isinstance(predicates, dict), 'invalid predicate bindings')
    names = [b[f] for f in ('rust_operation_symbol', 'rust_constants_symbol', 'rust_program_symbol')]
    names += list(predicates.values())
    names += [b['rust_operation_symbol'] + suffix for suffix in ('_INPUTS', '_CLASSIFICATIONS')]
    for name in names:
        require(isinstance(name, str) and re.fullmatch('[A-Z][A-Z0-9_]*', name), 'invalid Rust symbol')
        require(name not in symbols, f'duplicate binding symbol: {name}')
        symbols.add(name)
    require(op['kind'] == 'formula' and not op['relations'], 'unsupported scalar formula/relations')
    integer(op['id'], 2**32 - 1, 'operation id', 1)
    integer(op['revision'], 65535, 'revision', 1)
    require(0 < len(op['inputs']) <= 12 and len(op['outputs']) == 1, 'unsupported scalar arity')
    output = op['outputs'][0]
    require(set(output) <= {'name', 'semantic', 'unit_rule', 'shape'}
            and output.get('shape', 'scalar') == 'scalar'
            and output['unit_rule'] == 'dimensionless', 'unsupported scalar output')
    policy = op['output_policy']
    classes = op['classifications']
    require(policy == dict(scale=policy['scale'], rounding='half_even', allow_scale_override=False,
                           allow_rounding_override=False, classification_required=bool(classes)),
            'unsupported scalar output policy')
    integer(policy['scale'], 18, 'output scale')
    constants = [rational(c) for c in op['constants']]
    actual = handwritten_array(rust, b['rust_constants_symbol'], 'WorkRational',
                               r'WorkRational::from_integer\(\s*(-?\d+)\s*\)')
    require(list(map(int, actual)) == constants, 'handwritten constant drift')
    require(len(op['programs']) == 1 and op['programs'][0]['output'] == output['name'],
            'unsupported scalar programs')
    check_program(rust, b['rust_program_symbol'], op['programs'][0]['instructions'], opcodes, op)
    require(len({c['key'] for c in classes}) == len(classes)
            and len({c['id'] for c in classes}) == len(classes)
            and set(predicates) == {c['key'] for c in classes}, 'classification binding coverage drift')
    require([c['priority'] for c in classes] == sorted(c['priority'] for c in classes),
            'classification priority order drift')
    symbol = b['rust_operation_symbol']
    lines = [f'const {symbol}_INPUTS: [InputDecl; {len(op["inputs"])}] = [']
    groups = {}
    input_names = set()
    def semantic(key):
        require(key in semantics, 'unsupported scalar semantic')
        return integer(semantics[key]['id'], 255, 'semantic id')
    def quote(value):
        require(isinstance(value, str) and value.isascii()
                and all(ord(c) >= 32 for c in value), 'unsupported metadata string')
        return json.dumps(value)
    for inp in op['inputs']:
        require(set(inp) <= {'name', 'shape', 'semantic', 'unit_namespace', 'same_unit_group',
                             'unit_required', 'constraints'} and inp['shape'] == 'scalar',
                'unsupported scalar input')
        require(re.fullmatch('[a-z][a-z0-9_]*', inp['name']) and inp['name'] not in input_names,
                'invalid or duplicate input name')
        input_names.add(inp['name'])
        require(type(inp['unit_required']) is bool, 'invalid unit requirement')
        group = inp.get('same_unit_group')
        if group is not None:
            require(isinstance(group, str) and bool(group), 'invalid unit group')
            groups.setdefault(group, len(groups) + 1)
        constraints = inp['constraints']
        require(len(constraints) <= 1, 'unsupported scalar constraints')
        kind, value, detail = 'None', 0, 0
        if constraints:
            c = constraints[0]
            kinds = {'gt': 'GreaterThan', 'ge': 'GreaterOrEqual', 'ne': 'NotEqual', 'nonzero': 'NotEqual'}
            require(c['kind'] in kinds and set(c) == ({'kind', 'detail_id'} if c['kind'] == 'nonzero'
                                                     else {'kind', 'value', 'detail_id'}),
                    'unsupported scalar constraint')
            kind = kinds[c['kind']]
            value = rational(c.get('value', '0'))
            detail = integer(c['detail_id'], 65535, 'constraint detail id')
        values = dict(name=quote(inp['name']), semantic_kind=semantic(inp['semantic']),
                      same_unit_group=groups.get(group, 0), unit_required=str(inp['unit_required']).lower(),
                      constraint='ConstraintKind::' + kind,
                      constraint_value=f'WorkRational::from_integer({value})', detail_id=detail)
        lines += ['    InputDecl {'] + [f'        {k}: {v},' for k, v in values.items()] + ['    },']
    lines += ['];', '', f'const {symbol}_CLASSIFICATIONS: [ClassificationDecl; {len(classes)}] = [']
    for c in classes:
        require(set(c) == {'id', 'key', 'priority', 'output_index', 'program'},
                'unsupported classification fields')
        integer(c['id'], 65535, 'classification id', 1)
        integer(c['priority'], 65535, 'classification priority')
        require(type(c['output_index']) is int and c['output_index'] == 0, 'unsupported classification output')
        check_program(rust, predicates[c['key']], c['program'], opcodes, op, predicate=True)
        lines += ['    ClassificationDecl {', f'        id: {c["id"]},',
                  f'        key: {quote(c["key"])},', f'        program: &{predicates[c["key"]]},', '    },']
    signature = op['key'] + '(' + ','.join(i['name'] for i in op['inputs']) + ')'
    lines += ['];', '', f'/// `{signature}`.', f'pub static {symbol}: OperationDecl = OperationDecl {{']
    values = dict(id=op['id'], revision=op['revision'], key=quote(op['key']), signature=quote(signature),
                  method=quote(op['method']), inputs=f'&{symbol}_INPUTS', constants='&' + b['rust_constants_symbol'],
                  program='&' + b['rust_program_symbol'], classifications=f'&{symbol}_CLASSIFICATIONS',
                  output_semantic_kind=semantic(output['semantic']), output_scale=policy['scale'],
                  rounding_mode='RoundingMode::HalfEven')
    return lines + [f'    {k}: {v},' for k, v in values.items()] + ['};', '']


def outputs(root=ROOT):
    descriptors = load(root / 'spec/capabilities/domain-descriptors.json')['domains']
    generated = {}
    for domain, descriptor in sorted(descriptors.items()):
        source = load(root / descriptor['semantic_source'])
        bindings = load(root / descriptor['implementation_bindings'])
        operations = bindings['operations']
        by_key = {op['key']: op for op in source['operations']}
        require(len(by_key) == len(source['operations']), 'duplicate source key')
        require(len({op['id'] for op in source['operations']}) == len(source['operations']),
                'duplicate source operation id')
        require(len({b['key'] for b in operations}) == len(operations)
                and {b['key'] for b in operations} == set(by_key), 'source/binding coverage drift')
        require(len({b['cargo_feature'] for b in operations}) == len(operations),
                'duplicate scalar operation cargo feature')
        specialization = descriptor['specialization_feature']
        prefix = specialization.removesuffix('-specialized')
        validate_features(operations, root, prefix, specialization)
        if bindings['format'] == 'exactscope.statistics.kernel-bindings':
            require(domain == 'statistics' and bindings.get('domain') == 'statistics'
                    and bindings.get('format_version') == '0.1',
                    'invalid Statistics descriptor/binding identity')
            require(Path(descriptor['semantic_source']) == STATISTICS_PACK
                    and Path(descriptor['implementation_bindings']) == STATISTICS_BINDINGS
                    and specialization == 'stats-specialized',
                    'Statistics descriptor diverges from Statistics generator authority')
            continue
        require(bindings['format'] == 'exactscope.economics.operation-bindings'
                and bindings['domain'] == domain and bindings['format_version'] == '0.1',
                'unsupported scalar implementation bindings')
        require(re.fullmatch('[a-z][a-z0-9_]*', domain), 'invalid domain identifier')

        operation_symbols = [b['rust_operation_symbol'] for b in operations]
        require(len(set(operation_symbols)) == len(operation_symbols), 'duplicate operation symbol')
        rust = (root / 'crates/exactscope-kernel/src/operation.rs').read_text(encoding='utf-8')
        opcodes = registry(root, 'vm-opcodes')
        semantics = registry(root, 'semantic-kinds')
        lines = ['// @generated by tools/generate_domain_metadata.py; DO NOT EDIT.',
                 '// Metadata only; constants and VM programs remain handwritten.', '']
        symbols = set()
        for b in sorted(operations, key=lambda b: b['key']):
            lines += scalar_metadata(by_key[b['key']], b, rust, opcodes, semantics, symbols)
        lines += [f'/// Returns a reviewed {domain} operation selected into this build.',
                  f'#[cfg(feature = "{specialization}")]', '#[must_use]',
                  f"pub fn {domain}_selected_operation_by_key(key: &[u8]) -> Option<&'static OperationDecl> {{",
                  '    match key {']
        for b in sorted(operations, key=lambda b: b['key']):
            lines += [f'        #[cfg(feature = "{b["cargo_feature"]}")]',
                      f'        b"{b["key"]}" => Some(&{b["rust_operation_symbol"]}),']
        lines += ['        _ => None,', '    }', '}', '']
        generated[Path(f'crates/exactscope-kernel/src/{domain}_selection.generated.rs')] = '\n'.join(lines)
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    try:
        for relative, content in outputs().items():
            path = ROOT / relative
            if args.check:
                require(path.exists() and path.read_bytes() == content.encode(), f'stale {relative}')
            else:
                path.write_text(content, encoding='utf-8', newline='\n')
        print('Domain operation selection and specialization feature wiring verified.')
    except (ValueError, KeyError, TypeError, OSError) as error:
        print(f'Domain metadata: {error}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
